 - hosts: my_vm
   become: yes
   tasks:
    - name: Pull MySQL Docker image for Ibtahaj
      community.docker.docker_image:
        name: mysql
        tag: latest
        source: pull

    - name: Run MySQL container for Ibtahaj
      community.docker.docker_container:
        name: mysql-ibtahaj
        image: mysql:latest
        state: started
        env:
          MYSQL_ROOT_PASSWORD: "root_password"
          MYSQL_DATABASE: "zabbix"
          MYSQL_USER: "zabbix"
          MYSQL_PASSWORD: "zabbix"
        ports:
          - "3307:3306"

    - name: Pull Zabbix Docker image for Ibtahaj
      community.docker.docker_image:
        name: zabbix/zabbix-server-mysql
        tag: latest
        source: pull

    - name: Run Zabbix container for Ibtahaj
      community.docker.docker_container:
        name: zabbix-ibtahaj
        image: zabbix/zabbix-server-mysql:latest
        state: started
        ports:
          - "8084:80"
          - "10053:10051"
        env:
          DB_SERVER_HOST: "mysql-ibtahaj"
          MYSQL_USER: "zabbix"
          MYSQL_PASSWORD: "zabbix"
          MYSQL_DATABASE: "zabbix"

    - name: Pull Nagios Docker image for Ibtahaj
      community.docker.docker_image:
        name: jasonrivers/nagios
        tag: latest
        source: pull

    - name: Run Nagios container for Ibtahaj
      community.docker.docker_container:
        name: nagios-ibtahaj
        image: jasonrivers/nagios:latest
        state: started
        ports:
          - "8085:80"

    - name: Pull Prometheus Docker image for Ibtahaj
      community.docker.docker_image:
        name: prom/prometheus
        tag: v2.30.3
        source: pull

    - name: Run Prometheus container for Ibtahaj
      community.docker.docker_container:
        name: prometheus-ibtahaj
        image: prom/prometheus:v2.30.3
        state: started
        ports:
          - "8086:9090"
